name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        # Check if there are any previous commits
        if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
          # Get the list of modified or added Python files
          files=$(git diff --name-only HEAD^ HEAD | grep '\.py$')
        else
          # If no previous commit, check the current commit
          files=$(git diff --name-only --cached | grep '\.py$')
        fi
        
        echo "files: $files"
        if [ -n "$files" ]; then
          pylint $files
        else
          echo "No Python files to lint."
        fi
